# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed session.
# If you change this key, all old signed session will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff044c70a69c59a42431cb0ecf837233f8c58e5708cf7d74585d813f317ad5d18feb942429aa62d3e52cc125fc3cb2093c61b3b2202bd3ad65a2b20f890b9334

test:
  secret_key_base: 8fbc745cda82d8f122e4afddc7c1628b728fa346104dfc5224e77965cd1f2257b137e6403e6f6f5591702ffd5859039bff07619b1ce08ba69a61b645a91b21b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
